// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5I0ptL953255LGbC2XwRGIk5ea2WZhf8',
    appId: '1:343871007275:android:09bc6a4717065247f2d86e',
    messagingSenderId: '343871007275',
    projectId: 'attendnce-staff',
    databaseURL: 'https://attendnce-staff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendnce-staff.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg32cYmG0TkhEdcALhEiAmjvvd8ef8ZvI',
    appId: '1:343871007275:web:43257f9206fbf67ff2d86e',
    messagingSenderId: '343871007275',
    projectId: 'attendnce-staff',
    authDomain: 'attendnce-staff.firebaseapp.com',
    databaseURL: 'https://attendnce-staff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendnce-staff.firebasestorage.app',
    measurementId: 'G-21P64Z6YMZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTTSyMQCrUp6kfetriAQQWqiMyWiydYY',
    appId: '1:343871007275:ios:039e29c3c520cbd8f2d86e',
    messagingSenderId: '343871007275',
    projectId: 'attendnce-staff',
    databaseURL: 'https://attendnce-staff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendnce-staff.firebasestorage.app',
    iosClientId: '343871007275-l0g7m4bn7bj11qctpjfltir99m7gh79p.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTTSyMQCrUp6kfetriAQQWqiMyWiydYY',
    appId: '1:343871007275:ios:039e29c3c520cbd8f2d86e',
    messagingSenderId: '343871007275',
    projectId: 'attendnce-staff',
    databaseURL: 'https://attendnce-staff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendnce-staff.firebasestorage.app',
    iosClientId: '343871007275-l0g7m4bn7bj11qctpjfltir99m7gh79p.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg32cYmG0TkhEdcALhEiAmjvvd8ef8ZvI',
    appId: '1:343871007275:web:e0d584dbf94bda6cf2d86e',
    messagingSenderId: '343871007275',
    projectId: 'attendnce-staff',
    authDomain: 'attendnce-staff.firebaseapp.com',
    databaseURL: 'https://attendnce-staff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attendnce-staff.firebasestorage.app',
    measurementId: 'G-JDC4V93VDY',
  );

}